# Generated by Django 4.1.2 on 2022-10-14 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPlaced',
            new_name='OrderPlace',
        ),
    ]
